baseURL = "https://www.financesarthi.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Finance Sarthi"
[markup.goldmark.renderer]
unsafe = true
